name: Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
    - name: Run deployment script - 1
      run: |
        ssh -i keyfile -o StrictHostKeyChecking=no ubuntu@ec2-3-0-18-220.ap-southeast-1.compute.amazonaws.com << 'EOF'
          cd staff-management-3
          git pull origin main
          npm install
          pm2 delete all || true
          pm2 start dist/consumer.js --name “email-scanner-consumer”
          pm2 start dist/consumer.js --name “email-scanner-consumer-1”
        EOF
    - name: Run deployment script - 2
      run: |
        ssh -i keyfile -o StrictHostKeyChecking=no ubuntu@ec2-54-255-206-147.ap-southeast-1.compute.amazonaws.com << 'EOF'
          cd staff-management-3
          git pull origin main
          npm install
          pm2 delete all || true
          pm2 start dist/server.js --name “email-scanner-server”
          pm2 start dist/consumer.js --name “email-scanner-consumer”
          pm2 start dist/consumer.js --name “email-scanner-consumer-1”
        EOF

    - name: Clean up
      run: |
        rm -f keyfile
        rm -f ~/.ssh/known_hosts

       